const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';
const NEW_ATTACHMENTS = 'NEW_ATTACHMENT';
const NEW_MESSAGE = 'NEW_MESSAGE';

export { ALERT, REFETCH_CHATS ,NEW_ATTACHMENTS, NEW_MESSAGE};