const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';
const NEW_ATTACHMENTS = 'NEW_ATTACHMENT';
const NEW_MESSAGE = 'NEW_MESSAGE';
const NEW_REQUEST = 'NEW_REQUEST';
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT"

export { ALERT, REFETCH_CHATS ,NEW_ATTACHMENTS, NEW_MESSAGE, NEW_REQUEST ,NEW_MESSAGE_ALERT};